name       : dfu-programmer 
version    : 0.7.2
release    : 1
source     :
    - https://netcologne.dl.sourceforge.net/project/dfu-programmer/dfu-programmer/0.7.2/dfu-programmer-0.7.2.tar.gz : 1db4d36b1aedab2adc976e8faa5495df3cf82dc4bf883633dc6ba71f7c4af995
license    : GPL-2.0-or-later 
component  : programming.tools 
summary    : Device Firmware Update based USB programmer for Atmel chips with a USB bootloader. 
description: |
    dfu-programmer is an implementation of the Device Firmware Upgrade class USB driver that enables firmware upgrades for various USB enabled (with the correct bootloader) Atmel chips.
builddeps  :
    - libusb-devel
setup      : |
    ./bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
